# -*- coding: utf-8 -*-
"""ExtractFirstNameLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X3jSlgR5Y_b3vsLDfXqrlF81aCQHE0on
"""

def extract_first_name():
  full_name = input("Please enter your full name :")
  first_name = ''
  j = ''
  for j in full_name:
    if not j == ' ':
      first_name = first_name + j
    else:
      print("Your first name is :", first_name)

extract_first_name()