# -*- coding: utf-8 -*-
"""ModularProgramLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ovlgyxrvr0JpsP1WyL2GWBq0nblJCqTH
"""

#Modular Program Louis Keller

def get_grade():
  grade1 = []
  question = input("Do you want to enter a grade ?:")
  while question == 'yes':
    grade = int(input("Enter a grade between 0 and 100 :"))
    grade1.append(grade)
    question = input("Do you want to enter another grade ?:")
  return grade1

def letter_grade(percentage_grade):
  print("Your final grade percentage is :", percentage_grade)
  if 90<=percentage_grade<=100:
    print("You passed with a Grade A")
  elif 80<=percentage_grade<=89:
    print("You passed with a Grade B")
  elif 70<=percentage_grade<=79:
    print("You passed with a Grade C")
  elif 60<=percentage_grade<=69:
    print("You passed with a Grade D")
  else:
    print("You didn't pass this class...")

def main():
  percentage_grade = 0
  i = 0
  for j in get_grade():
    percentage_grade = j + percentage_grade
    i = i + 1
  percentage_grade = percentage_grade/i
  letter_grade(percentage_grade)

main()