# -*- coding: utf-8 -*-
"""NestedLoopLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k-7YU61hnTCaTwr7cIvofxE2eXJSTKyd
"""

#def inside(number):
  #i = 0
  #sum = 0
  #while i <= number:
    #sum = sum + number
    #i = i + 1
  #return sum

def nested_loop():
  outer_loop = int(input("Enter range of outside loop :"))
  j = 1
  k = 1
  i = 0
  l = 1
  inside = 4
  sum = 0
  total = 0
  while j <= outer_loop:
    print("Outer loop value :", outer_loop-(outer_loop-k))
    while i < inside*l:
      number = float(input("Enter the inside number :"))
      sum = sum + number
      i = i + 1
    l = l + 1
    j = j + 1
    k = k + 1
  print("Total:", sum)


nested_loop()