# -*- coding: utf-8 -*-
"""TemperatureConversionLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16CbJXoKcfIvscjvHzk5xewfIOIokxurv
"""

def celsius_to_fahrenheit(celsius1):
  fahrenheit = celsius1*(9/5) + 32
  return fahrenheit

def fahrenheit_to_celsius(fahrenheit1):
  celsius = (fahrenheit1-32)*(5/9)
  return celsius

def main():
  question = input("Press '1' to convert Celsius to Fahrenheit or '2' to convert Fahrenheit to celsius :")
  if question == '1':
    celsius1 = float(input("Enter Temperature in Celsius :"))
    print(celsius1, "degre Celsius is equal to", celsius_to_fahrenheit(celsius1), "degre Fahrenheit")
  else:
    fahrenheit1 = float(input("Enter Temperature in Fahrenheit :"))
    print(fahrenheit1, "degre Fahrenheit is equal to", fahrenheit_to_celsius(fahrenheit1), "degre Celsius")

main()